### PR TITLE
Add TypeScript support

### PR DESCRIPTION
**Pull request by tetradice**
I added a TypeScript type declaration (`index.d.ts`) so that you can use it with TypeScript just by installing your middlewares. I'd be happy if you can merge them.

### CODE REVIEW

**Comment by sergey-shpak** [comment]
@tetradice hey, thanks for the PR, sorry I missed the notification about this PR. If it is still relevant, we can merge and release.

**Comment by tetradice** [comment]
@sergey-shpak  Hello, Thank you for the reply. I have responded to the latest version 0.0.9 after receiving your reply. If there is no problem, I would appreciate it if you could merge it.

**Comment by sergey-shpak** [comment]
@tetradice I'm not using typescript in my projects, so I can not test and cannot guarantee support of those definitions in the future versions, if it's ok for you, I'm ready to merge the PR

**Comment by tetradice** [comment]
@sergey-shpak Yes, it's okay to merge :+1:

If you receive an issue related to type definition, please contact me. I will try to respond within a few days as much as possible.

**Pull request merged**
